---
- name: Install Consul Service Discovery file
  become: true
  template:
    src: "consul.json.j2"
    dest: "/etc/consul/consul.d/prom_dnsmasq_exporter.json"
    owner: root
    group: root
    mode: 644
  notify: restart consul
  when: "{{dnsmasq_exporter_consul_discovery_enabled}}"
