---
- name: Install Consul Service Discovery file
  become: true
  file:
    path: "/etc/consul/consul.d/prom_dnsmasq_exporter.json"
    state: "{{dnsmasq_exporter_consul_discovery_enabled | ternary("file","absent")}}"
    owner: root
    group: root
    mode: 644
  notify: restart consul
